package com.agro.crm.features.dashboard;

public enum AuditAction {
    // Farmers
    FARMER_CREATED, FARMER_UPDATED, FARMER_DELETED, FARMER_STATUS_CHANGED,
    // Fields
    FIELD_CREATED, FIELD_BOUNDARIES_UPDATED, FIELD_DELETED,
    // Equipment
    EQUIPMENT_CREATED, EQUIPMENT_UPDATED, EQUIPMENT_ASSIGNED,
    EQUIPMENT_MAINTENANCE_START, EQUIPMENT_MAINTENANCE_END, EQUIPMENT_AUTO_MAINTENANCE,
    // Telemetry
    TELEMETRY_DEVICE_CONNECTED, TELEMETRY_DEVICE_DISCONNECTED, TELEMETRY_FUEL_DROP,
    // Shifts & Tasks
    TASK_CREATED, TASK_COMPLETED, LOG_SHIFT_OPEN, LOG_SHIFT_CLOSE,
    // Security
    USER_LOGIN, USER_ROLE_CHANGED
}
